package creditcardgame.lists;

import creditcardgame.models.Product;

import java.util.ArrayList;

public class ProductsManager {
    public static ArrayList<Product> getProducts() {
        ArrayList<Product> productList = new ArrayList<>();

        productList.add(new Product("Notebook", 3500.00));
        productList.add(new Product("Smartphone", 2500.00));
        productList.add(new Product("Tablet", 1200.00));
        productList.add(new Product("Monitor", 800.00));
        productList.add(new Product("Teclado", 150.00));
        productList.add(new Product("Mouse", 100.00));
        productList.add(new Product("Impressora", 600.00));
        productList.add(new Product("Cadeira Gamer", 1200.00));
        productList.add(new Product("Mesa de Escritório", 900.00));
        productList.add(new Product("Fone de Ouvido", 300.00));
        productList.add(new Product("Webcam", 250.00));
        productList.add(new Product("Microfone", 400.00));
        productList.add(new Product("HD Externo", 700.00));
        productList.add(new Product("SSD", 550.00));
        productList.add(new Product("Placa de Vídeo", 2000.00));
        productList.add(new Product("Processador", 1800.00));
        productList.add(new Product("Placa-mãe", 800.00));
        productList.add(new Product("Fonte", 350.00));
        productList.add(new Product("Caixa de Som", 400.00));
        productList.add(new Product("Roteador", 300.00));
        productList.add(new Product("Smart TV", 2800.00));
        productList.add(new Product("Console de Videogame", 2000.00));
        productList.add(new Product("Jogos de Videogame", 250.00));
        productList.add(new Product("Câmera Digital", 1500.00));
        productList.add(new Product("Drone", 2500.00));
        productList.add(new Product("Smartwatch", 900.00));
        productList.add(new Product("GPS", 700.00));
        productList.add(new Product("Lanterna", 100.00));
        productList.add(new Product("Bateria Externa", 150.00));
        productList.add(new Product("Carregador Portátil", 120.00));
        productList.add(new Product("Cabo HDMI", 50.00));
        productList.add(new Product("Cabo USB", 30.00));
        productList.add(new Product("Cartão de Memória", 100.00));
        productList.add(new Product("Pen Drive", 80.00));
        productList.add(new Product("Suporte para Celular", 50.00));
        productList.add(new Product("Capinha de Celular", 80.00));
        productList.add(new Product("Película Protetora", 50.00));
        productList.add(new Product("Estabilizador", 300.00));
        productList.add(new Product("No-Break", 800.00));
        productList.add(new Product("Organizador de Cabos", 60.00));
        productList.add(new Product("Repetidor de Sinal", 200.00));
        productList.add(new Product("Placa de Som", 400.00));
        productList.add(new Product("Mouse Pad", 30.00));
        productList.add(new Product("Balança Digital", 120.00));
        productList.add(new Product("Despertador Inteligente", 150.00));
        productList.add(new Product("Aquecedor Elétrico", 500.00));
        productList.add(new Product("Ventilador", 200.00));
        productList.add(new Product("Ar Condicionado", 3000.00));
        productList.add(new Product("Purificador de Ar", 1000.00));
        productList.add(new Product("Aspirador de Pó", 600.00));
        productList.add(new Product("Máquina de Lavar", 2000.00));
        productList.add(new Product("Geladeira", 3000.00));
        productList.add(new Product("Fogão", 1500.00));
        productList.add(new Product("Micro-ondas", 900.00));
        productList.add(new Product("Liquidificador", 400.00));
        productList.add(new Product("Batedeira", 350.00));
        productList.add(new Product("Torradeira", 150.00));
        productList.add(new Product("Fritadeira Elétrica", 600.00));
        productList.add(new Product("Cafeteira", 250.00));
        productList.add(new Product("Máquina de Costura", 800.00));
        productList.add(new Product("Secadora de Roupas", 1500.00));
        productList.add(new Product("Aquecedor de Água", 400.00));
        productList.add(new Product("Chuveiro Elétrico", 150.00));
        productList.add(new Product("Ferro de Passar", 200.00));
        productList.add(new Product("Escova Elétrica", 100.00));
        productList.add(new Product("Secador de Cabelo", 200.00));
        productList.add(new Product("Cortador de Cabelo", 150.00));
        productList.add(new Product("Máquina de Barbear", 100.00));
        productList.add(new Product("Produtos de Limpeza", 50.00));
        productList.add(new Product("Desinfetante", 30.00));
        productList.add(new Product("Sabão em Pó", 20.00));
        productList.add(new Product("Amaciante", 25.00));
        productList.add(new Product("Detergente", 15.00));
        productList.add(new Product("Limpador Multiuso", 20.00));
        productList.add(new Product("Desinfetante de Ar", 30.00));
        productList.add(new Product("Desodorizador", 15.00));
        productList.add(new Product("Vassoura", 25.00));
        productList.add(new Product("Rodo", 20.00));
        productList.add(new Product("Pano de Limpeza", 10.00));
        productList.add(new Product("Balde", 15.00));
        productList.add(new Product("Luvas de Limpeza", 10.00));
        productList.add(new Product("Papel toalha", 20.00));
        productList.add(new Product("Esponja de Limpeza", 5.00));
        productList.add(new Product("Recipiente para Armazenamento", 50.00));
        productList.add(new Product("Caixa de Som Bluetooth", 500.00));
        productList.add(new Product("Organizador de Escritório", 100.00));
        productList.add(new Product("Quadro Branco", 300.00));
        productList.add(new Product("Caneta Esferográfica", 5.00));
        productList.add(new Product("Caderno", 20.00));
        productList.add(new Product("Papel A4", 10.00));
        productList.add(new Product("Pasta para Documentos", 15.00));
        productList.add(new Product("Post-it", 10.00));
        productList.add(new Product("Regua", 5.00));
        productList.add(new Product("Lápis", 2.00));
        productList.add(new Product("Borrachas", 3.00));
        productList.add(new Product("Fichário", 30.00));
        productList.add(new Product("Marcadores de Texto", 20.00));
        productList.add(new Product("Canetas Coloridas", 15.00));
        productList.add(new Product("Agendas", 25.00));
        productList.add(new Product("Planilhas", 10.00));

        return productList;
    }

}
